### ISSUE TITLE
API does not conform to REST style

### ISSUE THREAD

**Issue by Vitineth** [ents-crew/uems-gateway#11]
Not sure if we are actually following the proper REST style but if we are, the UPDATE and DELETE endpoints should not be available from `/events` (they are here https://github.com/ents-crew/uems-gateway/blob/master/src/app.ts#L107-L126)

To follow the REST style and the API style described in https://github.com/ents-crew/uems-hub/blob/master/api.swagger.yaml we would need to move the endpoints to match the following:

|Endpoint|Method|Action|
|--|--|--|
|`/events`|GET|Fetches all events|
|`/events`|POST|Creates a new event|
|`/events/{id}`|GET|Fetches one event|
|`/events/{id}`|PATCH|Updates one event|
|`/events/{id}`|DELETE|Deletes one event|

Are we following the proper style or do we want to keep it implemented as it is and try and update the documentation and deviate from the 'normal' REST style?

**Comment by Lan2u** [comment]
Why is delete/patch being /events/ rather than /events/id not RESTFUL?

**Comment by Vitineth** [comment]
As far as I could tell, because you are acting on a specific entry rather than the collection you should be acting on the endpoint for that specific event, along the lines of:

> Sending an HTTP GET request to the collection URI retrieves a list of items in the collection. Each item in the collection also has its own unique URI.

(source: https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design)

Because REST doesn't actually have a proper standard we can do whatever we want but as I understand it, using `/events/{id}` ensures that requests are clearly different when they act on the collection than on an entry

**Comment by Lan2u** [comment]
> As far as I could tell, because you are acting on a specific entry rather than the collection you should be acting on the endpoint for that specific event, along the lines of:
> 
> > Sending an HTTP GET request to the collection URI retrieves a list of items in the collection. Each item in the collection also has its own unique URI.
> 
> (source: https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design)
> 
> Because REST doesn't actually have a proper standard we can do whatever we want but as I understand it, using `/events/{id}` ensures that requests are clearly different when they act on the collection than on an entry

Not convinced that having /events/ vs events/id is required to be RESTful - at least from what I've read of https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm#sec_5_2

**Comment by Lan2u** [comment]
> As far as I could tell, because you are acting on a specific entry rather than the collection you should be acting on the endpoint for that specific event, along the lines of:

We aren't just always acting on a single entity - what if multiple events are being updated in batch?

**Comment by Vitineth** [comment]
> > As far as I could tell, because you are acting on a specific entry rather than the collection you should be acting on the endpoint for that specific event, along the lines of:
> 
> We aren't guaranteed to just be always acting on a single entity - what if multiple events are being updated in batch?
> 
> It might be that we do enforce than in which case I agree /events/{id} is clearer / a better mechanism

Good point, in that case I'd probably have batch actions be performed against `/events` because you're acting on a collection and individual updates performed on `/events/{id}` but I don't know if that increases the complexity of the gateway. This would also set us up nicely for batch actions like we need in https://github.com/ents-crew/uems-hub/issues/9.

**Comment by Lan2u** [comment]
> > > As far as I could tell, because you are acting on a specific entry rather than the collection you should be acting on the endpoint for that specific event, along the lines of:
> > 
> > 
> > We aren't guaranteed to just be always acting on a single entity - what if multiple events are being updated in batch?
> > It might be that we do enforce than in which case I agree /events/{id} is clearer / a better mechanism
> 
> Good point, in that case I'd probably have batch actions be performed against `/events` because you're acting on a collection and individual updates performed on `/events/{id}` but I don't know if that increases the complexity of the gateway. This would also set us up nicely for batch actions like we need in [ents-crew/uems-hub#9](https://github.com/ents-crew/uems-hub/issues/9).

On thinking about it we will rarely need to batch update/delete/add but we will definitely need to batch read

**Comment by Vitineth** [comment]
I can see batch update being useful for import actions unless we create a dedicated import endpoint which takes some CSV/JSON and handles it all on its own. It's up to you, just thought I'd raise it from other APIs that I've seen (ie Stripe https://stripe.com/docs/api/customers) because it makes a nice division about what your actions are impacting (a collection vs an entity)

**Comment by Lan2u** [comment]
> I can see batch update being useful for import actions unless we create a dedicated import endpoint which takes some CSV/JSON and handles it all on its own. It's up to you, just thought I'd raise it from other APIs that I've seen (ie Stripe https://stripe.com/docs/api/customers) because it makes a nice division about what your actions are impacting (a collection vs an entity)

I've kinda been using https://www.reddit.com/dev/api/#POST_api_comment as the API I've been thinking about when making decisions for this app. 

I don't want to do server side batch processing as of yet as it raises questions about the atomicity of the request (and we aren't at a state that we can make guarantees yet) - best to just get the client to deal with the conversion.

Having /events only for getting events and then events/id for update and delete might be more confusing and less RESTful than just having the space /events interface for all

**Comment by Vitineth** [comment]
> Having /events only for getting events and then events/id for update and delete might be more confusing and less RESTful than just having the same /events interface for all

I'm not against using `/events` for everything, just flagging it against what tends to be the accepted form. Tbh I'd say the reddit API isn't fantastic on its own as it has a really inconsistent structure (in places it uses verbs to describe the actions like it should but stuff like the comments use action endpoints which are generally frowned upon when using REST apis. Most stuff I've read about designing APIs makes a point to divide up your collections and your resources so `/events` is your collection and therefore should only have collection against against it and your resources are `/events/{id}` and should only have actions that affect that specific resource against it (Swagger: https://swagger.io/blog/api-design/api-design-best-practices/ and Microsoft: https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#9-collections). We can leave it as it is for now but it is something that I would look to address in the future in a `v2` of the API.

**Comment by Lan2u** [comment]
> > Having /events only for getting events and then events/id for update and delete might be more confusing and less RESTful than just having the same /events interface for all
> 
> I'm not against using `/events` for everything, just flagging it against what tends to be the accepted form. Tbh I'd say the reddit API isn't fantastic on its own as it has a really inconsistent structure (in places it uses verbs to describe the actions like it should but stuff like the comments use action endpoints which are generally frowned upon when using REST apis. Most stuff I've read about designing APIs makes a point to divide up your collections and your resources so `/events` is your collection and therefore should only have collection against against it and your resources are `/events/{id}` and should only have actions that affect that specific resource against it (Swagger: https://swagger.io/blog/api-design/api-design-best-practices/ and Microsoft: https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#9-collections). We can leave it as it is for now but it is something that I would look to address in the future in a `v2` of the API.

How is specifying the API in openAPI going? Perhaps the best move would be to get a draft of that and then we can discuss stuff based around the draft before we go any further with adding more to the API (we are now at a point in the API we can do everything we need to do for a bare minimum system meaning we can start writing more tests and setup better devops and security).

**Comment by Lan2u** [comment]
Closing this as it is about to be super-seeded by the issues generated by the preliminary (v0) API spec.
