### ISSUE TITLE
[API] Event Endpoint

### ISSUE THREAD

**Issue by Lan2u** [ents-crew/uems-gateway#13]
As per the specification the following API calls need to be defined (or re-defined with correct return status)

- [ ] Delete an event
- [ ] Get list of files related to the event
- [ ] Update event details
- [ ] Create an event
- [ ] Retrieve an event

More will be added as they are moved over from the spec / discussed.

This relates to the v0 API specification:
https://xiomi.stoplight.io/docs/uems-gateway-api/reference/kill-me.yaml/paths/~1ents/post

**Comment by Lan2u** [comment]
@Vitineth

**Comment by Vitineth** [comment]
This should be resolved through paths:
* **Delete an event**: `[DELETE]: /api/event/{id}`
* **Get list of files related to the event**: `[GET] /api/event/{id}/files`
* **Update event details**: `[PUT] /api/event/{id}`
* **Create an event**: `[POST] /api/event`
* **Retrieve an event**: `[GET] /api/event/{id}` and `[GET] /api/event`
